<?php
/**
 * @file
 * Export and delete webform submissions with in the date range.
 */

/**
 * Implements hook_permission().
 */
function _d7_webform_submissions_bulk_delete_permission() {
  return array(
    'access administration menu' => array(
      'title' => t('Access Webform Data Export'),
      'description' => t('Access the Webform Data Export configuration admin pages'),
    ),
  );
}
/**
 * Implements hook_menu().
 */
function _d7_webform_submissions_bulk_delete_menu() {
  $items = array();
  $items['node/%webform_menu/webform-results/bulk-delete'] = array(
    'title' => 'Bulk Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_data_export_form'),
    'access arguments' => array('access administration menu'),
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
/**
 * Implements hook_form().
 */
function _d7_webform_submissions_bulk_delete_form($form, $form_state) {
  if (!isset($form_state['delete_submit']['submit'])) {
    $date_attributes = array(
      'placeholder' => format_date(REQUEST_TIME, 'custom', webform_date_format('short'))
    );
    $form['delete_start_date'] = array(
      '#title'       => t('Start Date'),
      '#type' => 'textfield',
      '#attributes' => $date_attributes,
    );
    $form['delete_end_date'] = array(
      '#title'       => t('End date'),
      '#type' => 'textfield',
      '#attributes' => $date_attributes,
    );
    $form['delete_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Delete'),
      '#submit' => array('_d7_webform_submissions_bulk_delete_submit'),
    );
    return $form;
  }
  else {
    $path = current_path();
    return confirm_form($form, t("Do you really want to make the submissions to delete?"), $path, t("Warning, this is the last step before form gets submitted"), t("Proceed?"));
  }
  return $form;
}
/**
 * Implementation of batch creation().
 */
function _d7_webform_submissions_bulk_delete_form_submit($form, &$form_state) {
  if (!isset($form_state['delete_submit']['submit'])) {
    $form_state['delete_submit']['submit'] = TRUE;
    $form_state['rebuild'] = TRUE;
    $form_state['delete_submit']['original_form'] = $form_state['values'];
  }
  else {
    $batch = webform_data_export_delete_webform_submission_batch($form, $form_state);
    batch_set($batch);
    $nid = check_plain(arg(1));
    batch_process('node/' . $nid . '/webform-results/bulk-delete');
  }
}
/**
 * Implementation of batch queue().
 */
function _d7_webform_submissions_bulk_delete_webform_submission_batch($form, &$form_state) {
  $operations = array();
  $nid = check_plain(arg(1));
  $start_date = strtotime(check_plain($form_state['delete_submit']['original_form']['delete_start_date']));
  $end_date = strtotime(check_plain($form_state['delete_submit']['original_form']['delete_end_date'])) + 23 * 3600;
  $query = db_select('webform_submissions', 'submission');
  $query->fields('submission', array('sid'));
  $query->condition('submission.nid', $nid);
  $query->condition('submission.submitted', $start_date, '>=');
  $query->condition('submission.submitted', $end_date, '<=');
  $sid = $query->execute()->fetchAll();
  foreach ($sid as $submission_id) {
    $operations[] = array(
      'webform_data_export_delete_webform_submission_process', array($submission_id->sid),
    );
  }
  $batch = array(
    'init_message' => t('Initializing...'),
    'title' => t('Submission Deletion in progress...'),
    'operations' => $operations,
    'progress_message' => t('@current Submission Deleted out of @total.'),
    'error_message' => t('An Error has occurred!'),
    'finished' => 'webform_data_export_delete_webform_submission_finished',
  );
  return $batch;
}
/**
 * Implementation of batch context().
 */
function _d7_webform_submissions_bulk_delete_webform_submission_process($submission_id, &$context) {
  webform_data_export_delete_webform_submission_action($submission_id, $context, 'content-id');
}
/**
 * Implementation of batch success().
 */
function _d7_webform_submissions_bulk_delete_webform_submission_finished($success, $results, $operations) {
  if (isset($results['success'])) {
    if (count($results['success']) > 0) {
      drupal_set_message(t('@count submissions has been deleted', array('@count' => count($results['success']))));
    }
  }
}
/**
 * Implementation of batch process().
 */
function _d7_webform_submissions_bulk_delete_webform_submission_action($submission_id, &$context) {
  db_delete('webform_submitted_data')
    ->condition('sid', $submission_id)
    ->execute();
  db_delete('webform_submissions')
    ->condition('sid', $submission_id)
    ->execute();
}
